apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-torrent.fullname" . }}
  labels:
    {{- include "simple-torrent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-torrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-torrent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "simple-torrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: copy
        image: alpine:latest
        command: ["cp", "/tmp/simple-torrent/config.json", "/etc/simple-torrent/config.json"]
        volumeMounts:
        - name: temp
          mountPath: /tmp/simple-torrent
        - name: config
          mountPath: /etc/simple-torrent
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cloud-torrent", "-c", "/etc/simple-torrent/config.json"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: downloads
            mountPath: /downloads
          - name: config
            mountPath: /etc/simple-torrent
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: {{ .Values.existingClaim }}
      - name: temp
        configMap:
          name: simple-torrent-config
      - name: config
        emptyDir: {}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
